import Backbone from "@/components/molecules/Backbone";
import Head from "next/head";





export default function backbone() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Backbone/>
      
    </main>
  </>
  )
}
