import Bouyee from "@/components/molecules/Bouyee";
import Head from "next/head";





export default function bouyee() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/muse favicon.png" />
      </Head>
    <main>
      <Bouyee/>
      
    </main>
  </>
  )
}
