import Head from "next/head";
import Headline from '@/components/molecules/Headline.jsx';
import ProjectCards from "@/components/molecules/ProjectCards";


export default function cases() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Headline text="OUR WORK" info="At MUSE, we're dedicated to delivering excellence in every project. We listen closely to your needs, crafting solutions that surpass expectations. Your satisfaction is our priority, driving us to achieve the highest standards of quality."/>
      <ProjectCards/>
      
    </main>
  </>
  )
}
