import Head from "next/head";
import Headline from '@/components/molecules/Headline.jsx';
import ContactForm from "@/components/molecules/ContactForm";
import ContactDirect from "@/components/molecules/ContactDirect";



export default function cases() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/muse favicon.png" />
      </Head>
    <main>
      <Headline text="HIT US UP!" info="Want to be part of something extraordinary? With us, you get access to innovative and user-centric solutions that stand out. We understand your needs and strive to deliver tailored solutions that impress. Contact us today and let's create something amazing together!"/>
      <ContactForm/>
      <ContactDirect/>
    </main>
  </>
  )
}
