import Head from "next/head";
import IndexCards from "@/components/molecules/IndexCards";
import IndexHeader from "@/components/molecules/IndexHeader";


export default function Home() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/muse favicon.png" />
      </Head>
      <main>
        <IndexHeader/>
        <IndexCards/>
      </main>
    </>
  );
}
