import Head from "next/head";
import Vaeleur from "@/components/molecules/Vaeleur";




export default function vaeleur() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/muse favicon.png" />
      </Head>
    <main>
    <Vaeleur/>
      
    </main>
  </>
  )
}
