import Head from "next/head";
import WwoPage from "@/components/molecules/WwoPage"





export default function wwoContent() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
     <WwoPage introHeadlineText="OUR AIM WITH CONTENT CREATION" introText="At MUSE, content creation isn't just about producing material—it's about crafting experiences that resonate deeply with our audience. We understand that every piece of content we create is an opportunity to engage, inspire, and connect with our customers on a meaningful level. In essence, content creation isn't just a means to an end for us—it's the very essence of who we are. It's how we communicate, connect, and ultimately, thrive as a brand. And as long as our customers continue to inspire us, we'll never stop innovating and evolving to meet their ever-changing needs." video="/muse content video hvid.mp4" progImgOne="/psLogo.svg" progImgTwo="/aiLogo.svg" progImgThree="/lrLogo.svg" progImgFour="/aeLogo.svg" progHeadlineText="WE WORK IN..." progInfoText="At MUSE, collaboration isn't just about sharing files—it's about empowering our partners to customize and enhance our products to suit their unique needs. 
    By working in programs like Adobe, we not only streamline the file-sharing process but also provide our partners with the tools they need to tailor our products to their liking. Whether it's adjusting colors, fonts, or layouts, our meticulously organized files make it easy for them to make changes without compromising quality or consistency."/>
      
    </main>
  </>
  )
}
