import Head from "next/head";
import WwoPage from "@/components/molecules/WwoPage"





export default function wwoWeb() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
     <WwoPage introHeadlineText="OUR AIM WITH WEB DEVELOPMENT" introText="At MUSE, web development isn't just about building websites—it's about crafting digital experiences that resonate deeply with our audience. We understand that every line of code we write is an opportunity to engage, inspire, and connect with our users on a meaningful level. Central to our approach is the idea that web development should not only be functional and user-friendly but also aligned with the unique identity of our audience. We meticulously tailor our websites to fit seamlessly into their online journey, reflecting their preferences, values, and aspirations." imageUrlOne="/webMock.png" progImgOne="/vscLogo.webp" progImgTwo="/wpLogo.png" progHeadlineText="WE WORK IN..." progInfoText="We understand that every partnership is unique, and that's why we prioritize compatibility and adaptability in our development approach. Our commitment to using widely recognized technologies ensures that our partners can continue to refine and evolve our web products long after our collaboration has ended.So, whether you're looking to make minor adjustments or major enhancements, rest assured that our code is designed with your customization needs in mind. With MUSE, the possibilities for web development are endless."/>
      
    </main>
  </>
  )
}
