import Head from "next/head";
import WwoPage from "@/components/molecules/WwoPage"





export default function wwoUx() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
        <WwoPage introHeadlineText="OUR AIM WITH UX" introText="At MUSE, UX design isn't merely about crafting interfaces—it's about sculpting immersive journeys that deeply resonate with our users. We recognize that every interaction is an opportunity to captivate, empower, and forge genuine connections with our audience. For us, UX design embodies the essence of our brand—it's not just a process, but our very identity. It's how we communicate, empathize, and ultimately thrive in the digital landscape. Inspired by our users, we're committed to perpetual innovation, continuously evolving to anticipate and exceed their evolving expectations." video="/MUSE VIDEO - UX_UI.mp4" progImgOne="/vscLogo.webp" progImgTwo="/wpLogo.png" progHeadlineText="WE WORK IN..." progInfoText="At MUSE, collaboration isn't just about file sharing—it's about empowering our partners to customize and enhance our products to meet their unique needs. Leveraging platforms like WordPress and Google Analytics, we facilitate seamless collaboration, providing our partners with the tools they need to tailor our offerings to their preferences. Whether it's tweaking designs, optimizing content, or refining user experiences, our streamlined processes ensure that partners can make changes efficiently without sacrificing quality or consistency."/>
      
    </main>
  </>
  )
}
