import Head from "next/head";
import Headline from '@/components/molecules/Headline.jsx';
import WwoCards from '@/components/molecules/WwoCards';

export default function offer() {
  return (
    <>
      <Head>
        <title>MUSE Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Headline text="THE SKY IS THE LIMIT" info="We offer a wide range of expertise within the multimedia world. Everything from content creation, UX and web development. we cater to your needs and desires and will do everything in our power to deliver products that are up to you and your brands standards."/>
      <WwoCards/>
    </main>
  </>
  )
}
